stage:
  "/":
  - type: SourceFile
    path: "{{cargo.target_directory}}/debug/cargo-tarball"
  "/completions":
  - type: SourceFiles
    path: "{{cargo.target_directory}}/debug/build/cargo-tarball-63c1f7d9f2ae9bcc/out/completions"
    pattern: "*"
