stage:
  "/":
  - type: SourceFile
    path: "{{cargo.target_directory}}/debug/cargo-tarball"
  "/completions":
  - type: SourceFiles
    path: "{{cargo.target_directory}}/debug/build/cargo-tarball-b8d713fa01725c21/out/completions"
    pattern: "*"
